// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxgZ2_U-7Eivw_VHX9asd3AcGiG1Sfh8w',
    appId: '1:1069410864296:web:46ae51d9c22cd7b218869d',
    messagingSenderId: '1069410864296',
    projectId: 'my-calendar-app-v3',
    authDomain: 'my-calendar-app-v3.firebaseapp.com',
    storageBucket: 'my-calendar-app-v3.appspot.com',
    measurementId: 'G-J7XCZ3X86T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIGGND4a_JnJX6UbK9WCgAaD4MS2XDpcU',
    appId: '1:1069410864296:android:07a8e5a58bd2dc3618869d',
    messagingSenderId: '1069410864296',
    projectId: 'my-calendar-app-v3',
    storageBucket: 'my-calendar-app-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1365Lxm82YJdS0Bzx9zsk946PfTZxJI',
    appId: '1:1069410864296:ios:a11c33569db2241418869d',
    messagingSenderId: '1069410864296',
    projectId: 'my-calendar-app-v3',
    storageBucket: 'my-calendar-app-v3.appspot.com',
    iosBundleId: 'com.example.calendarCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg1365Lxm82YJdS0Bzx9zsk946PfTZxJI',
    appId: '1:1069410864296:ios:26953a555bcbe78518869d',
    messagingSenderId: '1069410864296',
    projectId: 'my-calendar-app-v3',
    storageBucket: 'my-calendar-app-v3.appspot.com',
    iosBundleId: 'com.example.calendarCrud.RunnerTests',
  );
}
